"""add_likes_table

Revision ID: 16ce6cfa73c9
Revises: 8f4c2b6d9a10
Create Date: 2026-07-07 09:21:40.941998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ce6cfa73c9'
down_revision: Union[str, Sequence[str], None] = '8f4c2b6d9a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'target_type'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='unique_like_per_user_per_target')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=True))
        batch_op.drop_column('nick_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nick_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('nickname')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_target_id'))

    op.drop_table('likes')
    # ### end Alembic commands ###
